#example
import json
file = open('sample-data.json', 'r')
#print(file.read())
json_data = json.loads(file.read())
print("Interface Status")
print("================================================================================")
print('DN                                                 Description           Speed    MTU')
print("-------------------------------------------------- --------------------  ------  ------")
print(json_data['imdata'][0]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][1]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][2]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][3]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][4]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][5]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][6]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][7]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][8]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][9]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][10]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][11]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][12]['l1PhysIf']['attributes']['dn'], "                              ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][13]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][14]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][15]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][16]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])
print(json_data['imdata'][17]['l1PhysIf']['attributes']['dn'], "                             ", json_data['imdata'][0]['l1PhysIf']['attributes']['speed'], json_data['imdata'][0]['l1PhysIf']['attributes']['mtu'])


